//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionRule()
        {
            this.TaskSubmissionRules = new HashSet<TaskSubmissionRule>();
            this.TeamSubmissionRules = new HashSet<TeamSubmissionRule>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<bool> PayStatus { get; set; }
        public Nullable<bool> RegistrationStatus { get; set; }
        public Nullable<bool> ShowLate { get; set; }
        public Nullable<bool> ShowReport { get; set; }
        public Nullable<bool> SendEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSubmissionRule> TaskSubmissionRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSubmissionRule> TeamSubmissionRules { get; set; }
    }
}
