//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSubmissionRule
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int SubmissionRuleId { get; set; }
        public string SubmissionRuleUrl { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual SubmissionRule SubmissionRule { get; set; }
        public virtual Team Team { get; set; }
    }
}
