//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTaskSubmissionRule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public System.DateTime DueDate { get; set; }
        public int TaskId { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string SubmissionRuleUrl { get; set; }
        public Nullable<bool> PayStatus { get; set; }
        public Nullable<bool> RegistrationStatus { get; set; }
        public bool TeamPayStatus { get; set; }
        public Nullable<bool> TeamRegistrationStatus { get; set; }
        public Nullable<bool> ShowLate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<bool> ShowReport { get; set; }
        public Nullable<bool> SendEmail { get; set; }
    }
}
