//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public int GradeId { get; set; }
        public string Grade { get; set; }
        public Nullable<bool> Preliminary { get; set; }
        public Nullable<bool> OpenTaskTestPlan { get; set; }
        public string PaymentType { get; set; }
        public string PaymentTypeDescription { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<bool> RegisterForFlashTalk { get; set; }
    }
}
